AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "A template to create the GOV.UK One login Account Data backend infrastructure."

Parameters:
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"
  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"
  #VpcStackName:
  #  Type: String
  #  Description: >
  #    The name of the stack that defines the VPC in which these resources will
  #    run.
  #  Default: vpc
  Environment:
    Description: The name of the environment to deploy to (provided by the pipeline)
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  HomeTeamOwnerTagValue:
    Description: Value for the Owner Tag
    Type: String
    Default: govuk-accounts-tech@digital.cabinet-office.gov.uk
  ProductTagValue:
    Description: Value for the Product Tag
    Type: String
    Default: GOV.UK One Login
  SourceTagValue:
    Description: Value for the Source Tag
    Type: String
    Default: https://github.com/alphagov/di-account-data-backend/blob/main/infrastructure/template.yaml
  SystemTagValue:
    Description: Value for the System Tag
    Type: String
    Default: Account Management

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Resources:
  BackupWrapperKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: A backup key used to encrypt the data key for envelope encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow IAM to manage access to the key"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref HomeTeamOwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue
        - Key: Name
          Value: !Sub "${AWS::StackName}-BackupWrapperKey"

  BackupWrapperKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-BackupWrapperKey"
      TargetKeyId: !GetAtt BackupWrapperKey.Arn

  BackupWrappingKeyArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Root ARN of the acctount-management-backend AWS account"
      Name: !Sub "/${AWS::StackName}/${Environment}/AccountManagement/Backend/Root/ARN"
      Type: String
      Value: "arn:aws:iam::please-set-me-to-account-id:root"