name: Lint and test lambdas

on:
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}
  pull_request:

jobs:
  lint_and_test_hello_world:
    name: hello-world
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambdas/hello-world
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
