name: Sonarcloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud_hello_world:
    name: hello-world
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambdas/hello-world
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Generate coverage report
        run: npm test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./lambdas/hello-world
